// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewShore.Persistence;

namespace NewShore.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewShore.Domain.Model.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArrivalStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransportId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 8, 8, 1, 985, DateTimeKind.Local).AddTicks(9712),
                            DepartureStation = "BOG",
                            Price = 173703m,
                            TransportId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 10, 8, 1, 988, DateTimeKind.Local).AddTicks(9660),
                            DepartureStation = "BOG",
                            Price = 190851m,
                            TransportId = 2
                        },
                        new
                        {
                            Id = 3,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 13, 8, 1, 988, DateTimeKind.Local).AddTicks(9829),
                            DepartureStation = "BOG",
                            Price = 147335m,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 4,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 8, 8, 1, 988, DateTimeKind.Local).AddTicks(9838),
                            DepartureStation = "MED",
                            Price = 270685m,
                            TransportId = 4
                        },
                        new
                        {
                            Id = 5,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 11, 8, 1, 988, DateTimeKind.Local).AddTicks(9842),
                            DepartureStation = "MED",
                            Price = 229320m,
                            TransportId = 5
                        },
                        new
                        {
                            Id = 6,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 13, 8, 1, 988, DateTimeKind.Local).AddTicks(9860),
                            DepartureStation = "MED",
                            Price = 151898m,
                            TransportId = 6
                        },
                        new
                        {
                            Id = 7,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 6, 8, 1, 988, DateTimeKind.Local).AddTicks(9865),
                            DepartureStation = "CTG",
                            Price = 222903m,
                            TransportId = 7
                        },
                        new
                        {
                            Id = 8,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 11, 8, 1, 988, DateTimeKind.Local).AddTicks(9869),
                            DepartureStation = "CTG",
                            Price = 126846m,
                            TransportId = 8
                        },
                        new
                        {
                            Id = 9,
                            ArrivalStation = "CTG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 10, 8, 1, 988, DateTimeKind.Local).AddTicks(9872),
                            DepartureStation = "BOG",
                            Price = 150476m,
                            TransportId = 9
                        },
                        new
                        {
                            Id = 10,
                            ArrivalStation = "CTG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 13, 8, 1, 988, DateTimeKind.Local).AddTicks(9879),
                            DepartureStation = "BOG",
                            Price = 248798m,
                            TransportId = 10
                        },
                        new
                        {
                            Id = 11,
                            ArrivalStation = "PEI",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 6, 8, 1, 988, DateTimeKind.Local).AddTicks(9883),
                            DepartureStation = "BOG",
                            Price = 268263m,
                            TransportId = 11
                        },
                        new
                        {
                            Id = 12,
                            ArrivalStation = "PEI",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 12, 8, 1, 988, DateTimeKind.Local).AddTicks(9888),
                            DepartureStation = "BOG",
                            Price = 223667m,
                            TransportId = 12
                        },
                        new
                        {
                            Id = 13,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 6, 8, 1, 988, DateTimeKind.Local).AddTicks(9892),
                            DepartureStation = "PEI",
                            Price = 222275m,
                            TransportId = 13
                        },
                        new
                        {
                            Id = 14,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 29, 13, 8, 1, 988, DateTimeKind.Local).AddTicks(9896),
                            DepartureStation = "PEI",
                            Price = 253286m,
                            TransportId = 14
                        },
                        new
                        {
                            Id = 15,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 8, 8, 1, 988, DateTimeKind.Local).AddTicks(9900),
                            DepartureStation = "BOG",
                            Price = 246755m,
                            TransportId = 15
                        },
                        new
                        {
                            Id = 16,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 10, 8, 1, 988, DateTimeKind.Local).AddTicks(9968),
                            DepartureStation = "BOG",
                            Price = 218383m,
                            TransportId = 16
                        },
                        new
                        {
                            Id = 17,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 13, 8, 1, 988, DateTimeKind.Local).AddTicks(9973),
                            DepartureStation = "BOG",
                            Price = 205397m,
                            TransportId = 17
                        },
                        new
                        {
                            Id = 18,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 8, 8, 1, 988, DateTimeKind.Local).AddTicks(9982),
                            DepartureStation = "MED",
                            Price = 265874m,
                            TransportId = 18
                        },
                        new
                        {
                            Id = 19,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 11, 8, 1, 988, DateTimeKind.Local).AddTicks(9986),
                            DepartureStation = "MED",
                            Price = 105001m,
                            TransportId = 19
                        },
                        new
                        {
                            Id = 20,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 13, 8, 1, 988, DateTimeKind.Local).AddTicks(9990),
                            DepartureStation = "MED",
                            Price = 154703m,
                            TransportId = 20
                        },
                        new
                        {
                            Id = 21,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 6, 8, 1, 988, DateTimeKind.Local).AddTicks(9994),
                            DepartureStation = "CTG",
                            Price = 164648m,
                            TransportId = 21
                        },
                        new
                        {
                            Id = 22,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 11, 8, 1, 988, DateTimeKind.Local).AddTicks(9998),
                            DepartureStation = "CTG",
                            Price = 165319m,
                            TransportId = 22
                        },
                        new
                        {
                            Id = 23,
                            ArrivalStation = "CTG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 10, 8, 1, 989, DateTimeKind.Local).AddTicks(4),
                            DepartureStation = "BOG",
                            Price = 286596m,
                            TransportId = 23
                        },
                        new
                        {
                            Id = 24,
                            ArrivalStation = "CTG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 13, 8, 1, 989, DateTimeKind.Local).AddTicks(9),
                            DepartureStation = "BOG",
                            Price = 155053m,
                            TransportId = 24
                        },
                        new
                        {
                            Id = 25,
                            ArrivalStation = "PEI",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 6, 8, 1, 989, DateTimeKind.Local).AddTicks(14),
                            DepartureStation = "BOG",
                            Price = 108246m,
                            TransportId = 25
                        },
                        new
                        {
                            Id = 26,
                            ArrivalStation = "PEI",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 12, 8, 1, 989, DateTimeKind.Local).AddTicks(18),
                            DepartureStation = "BOG",
                            Price = 157859m,
                            TransportId = 26
                        },
                        new
                        {
                            Id = 27,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 6, 8, 1, 989, DateTimeKind.Local).AddTicks(22),
                            DepartureStation = "PEI",
                            Price = 205883m,
                            TransportId = 27
                        },
                        new
                        {
                            Id = 28,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 30, 13, 8, 1, 989, DateTimeKind.Local).AddTicks(26),
                            DepartureStation = "PEI",
                            Price = 276634m,
                            TransportId = 28
                        },
                        new
                        {
                            Id = 29,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 8, 8, 1, 989, DateTimeKind.Local).AddTicks(30),
                            DepartureStation = "BOG",
                            Price = 165642m,
                            TransportId = 29
                        },
                        new
                        {
                            Id = 30,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 10, 8, 1, 989, DateTimeKind.Local).AddTicks(34),
                            DepartureStation = "BOG",
                            Price = 104520m,
                            TransportId = 30
                        },
                        new
                        {
                            Id = 31,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 13, 8, 1, 989, DateTimeKind.Local).AddTicks(38),
                            DepartureStation = "BOG",
                            Price = 173565m,
                            TransportId = 31
                        },
                        new
                        {
                            Id = 32,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 8, 8, 1, 989, DateTimeKind.Local).AddTicks(43),
                            DepartureStation = "MED",
                            Price = 246902m,
                            TransportId = 32
                        },
                        new
                        {
                            Id = 33,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 11, 8, 1, 989, DateTimeKind.Local).AddTicks(47),
                            DepartureStation = "MED",
                            Price = 256023m,
                            TransportId = 33
                        },
                        new
                        {
                            Id = 34,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 13, 8, 1, 989, DateTimeKind.Local).AddTicks(54),
                            DepartureStation = "MED",
                            Price = 294531m,
                            TransportId = 34
                        },
                        new
                        {
                            Id = 35,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 6, 8, 1, 989, DateTimeKind.Local).AddTicks(268),
                            DepartureStation = "CTG",
                            Price = 221191m,
                            TransportId = 35
                        },
                        new
                        {
                            Id = 36,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 11, 8, 1, 989, DateTimeKind.Local).AddTicks(277),
                            DepartureStation = "CTG",
                            Price = 178487m,
                            TransportId = 36
                        },
                        new
                        {
                            Id = 37,
                            ArrivalStation = "CTG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 10, 8, 1, 989, DateTimeKind.Local).AddTicks(282),
                            DepartureStation = "BOG",
                            Price = 212495m,
                            TransportId = 37
                        },
                        new
                        {
                            Id = 38,
                            ArrivalStation = "CTG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 13, 8, 1, 989, DateTimeKind.Local).AddTicks(285),
                            DepartureStation = "BOG",
                            Price = 254912m,
                            TransportId = 38
                        },
                        new
                        {
                            Id = 39,
                            ArrivalStation = "PEI",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 6, 8, 1, 989, DateTimeKind.Local).AddTicks(290),
                            DepartureStation = "BOG",
                            Price = 254679m,
                            TransportId = 39
                        },
                        new
                        {
                            Id = 40,
                            ArrivalStation = "PEI",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 12, 8, 1, 989, DateTimeKind.Local).AddTicks(294),
                            DepartureStation = "BOG",
                            Price = 181934m,
                            TransportId = 40
                        },
                        new
                        {
                            Id = 41,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 6, 8, 1, 989, DateTimeKind.Local).AddTicks(298),
                            DepartureStation = "PEI",
                            Price = 267624m,
                            TransportId = 41
                        },
                        new
                        {
                            Id = 42,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 10, 31, 13, 8, 1, 989, DateTimeKind.Local).AddTicks(302),
                            DepartureStation = "PEI",
                            Price = 206069m,
                            TransportId = 42
                        });
                });

            modelBuilder.Entity("NewShore.Domain.Model.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("NamePasanger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailContact = "mariobot@hotmail.com",
                            FlightId = 10,
                            NamePasanger = "Mario Botero",
                            PhoneNumber = "5764821565"
                        },
                        new
                        {
                            Id = 2,
                            EmailContact = "cmejia@hotmail.com",
                            FlightId = 20,
                            NamePasanger = "Carolina gomez",
                            PhoneNumber = "5732456215"
                        },
                        new
                        {
                            Id = 3,
                            EmailContact = "mmejia@gmail.com",
                            FlightId = 30,
                            NamePasanger = "Maria Mejia",
                            PhoneNumber = "5755662245"
                        },
                        new
                        {
                            Id = 4,
                            EmailContact = "fernando23@gmail.com",
                            FlightId = 40,
                            NamePasanger = "Fernanda Ferrero",
                            PhoneNumber = "57545562"
                        },
                        new
                        {
                            Id = 5,
                            EmailContact = "cmejia@hotmail.com",
                            FlightId = 42,
                            NamePasanger = "Camilo Mejia",
                            PhoneNumber = "574455665"
                        });
                });

            modelBuilder.Entity("NewShore.Domain.Model.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightNumber = "EKYQGUS"
                        },
                        new
                        {
                            Id = 2,
                            FlightNumber = "TSEKHIW"
                        },
                        new
                        {
                            Id = 3,
                            FlightNumber = "LBOHBHL"
                        },
                        new
                        {
                            Id = 4,
                            FlightNumber = "PILWUWB"
                        },
                        new
                        {
                            Id = 5,
                            FlightNumber = "GAMFVFV"
                        },
                        new
                        {
                            Id = 6,
                            FlightNumber = "URJVQMW"
                        },
                        new
                        {
                            Id = 7,
                            FlightNumber = "AUWURDB"
                        },
                        new
                        {
                            Id = 8,
                            FlightNumber = "BQXDBYP"
                        },
                        new
                        {
                            Id = 9,
                            FlightNumber = "BNUMXRM"
                        },
                        new
                        {
                            Id = 10,
                            FlightNumber = "SSEMCBR"
                        },
                        new
                        {
                            Id = 11,
                            FlightNumber = "JFMLVOO"
                        },
                        new
                        {
                            Id = 12,
                            FlightNumber = "OOCCTZE"
                        },
                        new
                        {
                            Id = 13,
                            FlightNumber = "JPCUHFS"
                        },
                        new
                        {
                            Id = 14,
                            FlightNumber = "EOJTUJI"
                        },
                        new
                        {
                            Id = 15,
                            FlightNumber = "BRHPBJR"
                        },
                        new
                        {
                            Id = 16,
                            FlightNumber = "LKRGJAN"
                        },
                        new
                        {
                            Id = 17,
                            FlightNumber = "YRKDRII"
                        },
                        new
                        {
                            Id = 18,
                            FlightNumber = "DBRVVYF"
                        },
                        new
                        {
                            Id = 19,
                            FlightNumber = "QDSAFGM"
                        },
                        new
                        {
                            Id = 20,
                            FlightNumber = "XUNRQNY"
                        },
                        new
                        {
                            Id = 21,
                            FlightNumber = "ELOXFEG"
                        },
                        new
                        {
                            Id = 22,
                            FlightNumber = "WYPCBZY"
                        },
                        new
                        {
                            Id = 23,
                            FlightNumber = "PPTGKMU"
                        },
                        new
                        {
                            Id = 24,
                            FlightNumber = "HZFEUAB"
                        },
                        new
                        {
                            Id = 25,
                            FlightNumber = "XXLBVJZ"
                        },
                        new
                        {
                            Id = 26,
                            FlightNumber = "QDYQUZT"
                        },
                        new
                        {
                            Id = 27,
                            FlightNumber = "ECXDGOH"
                        },
                        new
                        {
                            Id = 28,
                            FlightNumber = "ETLFADW"
                        },
                        new
                        {
                            Id = 29,
                            FlightNumber = "LISKEFZ"
                        },
                        new
                        {
                            Id = 30,
                            FlightNumber = "BDBGQZY"
                        },
                        new
                        {
                            Id = 31,
                            FlightNumber = "MVPQNAD"
                        },
                        new
                        {
                            Id = 32,
                            FlightNumber = "WIANMTS"
                        },
                        new
                        {
                            Id = 33,
                            FlightNumber = "DZVUGCE"
                        },
                        new
                        {
                            Id = 34,
                            FlightNumber = "VFFQTUC"
                        },
                        new
                        {
                            Id = 35,
                            FlightNumber = "YVXQPIS"
                        },
                        new
                        {
                            Id = 36,
                            FlightNumber = "XVONCTP"
                        },
                        new
                        {
                            Id = 37,
                            FlightNumber = "ARXRLHY"
                        },
                        new
                        {
                            Id = 38,
                            FlightNumber = "EFLKWUQ"
                        },
                        new
                        {
                            Id = 39,
                            FlightNumber = "QKATGAX"
                        },
                        new
                        {
                            Id = 40,
                            FlightNumber = "MDXXKZF"
                        },
                        new
                        {
                            Id = 41,
                            FlightNumber = "DGGDJPV"
                        },
                        new
                        {
                            Id = 42,
                            FlightNumber = "NIYINEU"
                        });
                });

            modelBuilder.Entity("NewShore.Domain.Model.Flight", b =>
                {
                    b.HasOne("NewShore.Domain.Model.Transport", "Transport")
                        .WithMany("Flights")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewShore.Domain.Model.Ticket", b =>
                {
                    b.HasOne("NewShore.Domain.Model.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
