// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewShore.Persistence;

namespace NewShore.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewShore.Domain.Model.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArrivalStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransportId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 7, 23, 17, 645, DateTimeKind.Local).AddTicks(9438),
                            DepartureStation = "BOG",
                            Price = 116858m,
                            TransportId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 9, 23, 17, 649, DateTimeKind.Local).AddTicks(5079),
                            DepartureStation = "BOG",
                            Price = 149648m,
                            TransportId = 2
                        },
                        new
                        {
                            Id = 3,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 12, 23, 17, 649, DateTimeKind.Local).AddTicks(5216),
                            DepartureStation = "BOG",
                            Price = 108912m,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 4,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 7, 23, 17, 649, DateTimeKind.Local).AddTicks(5224),
                            DepartureStation = "MED",
                            Price = 122790m,
                            TransportId = 4
                        },
                        new
                        {
                            Id = 5,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 10, 23, 17, 649, DateTimeKind.Local).AddTicks(5227),
                            DepartureStation = "MED",
                            Price = 200726m,
                            TransportId = 5
                        },
                        new
                        {
                            Id = 6,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 12, 23, 17, 649, DateTimeKind.Local).AddTicks(5242),
                            DepartureStation = "MED",
                            Price = 293318m,
                            TransportId = 6
                        },
                        new
                        {
                            Id = 7,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 5, 23, 17, 649, DateTimeKind.Local).AddTicks(5246),
                            DepartureStation = "CTG",
                            Price = 200156m,
                            TransportId = 7
                        },
                        new
                        {
                            Id = 8,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 10, 23, 17, 649, DateTimeKind.Local).AddTicks(5250),
                            DepartureStation = "CTG",
                            Price = 168094m,
                            TransportId = 8
                        },
                        new
                        {
                            Id = 9,
                            ArrivalStation = "CTG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 9, 23, 17, 649, DateTimeKind.Local).AddTicks(5254),
                            DepartureStation = "BOG",
                            Price = 256355m,
                            TransportId = 9
                        },
                        new
                        {
                            Id = 10,
                            ArrivalStation = "CTG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 12, 23, 17, 649, DateTimeKind.Local).AddTicks(5259),
                            DepartureStation = "BOG",
                            Price = 106760m,
                            TransportId = 10
                        },
                        new
                        {
                            Id = 11,
                            ArrivalStation = "PEI",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 5, 23, 17, 649, DateTimeKind.Local).AddTicks(5262),
                            DepartureStation = "BOG",
                            Price = 268410m,
                            TransportId = 11
                        },
                        new
                        {
                            Id = 12,
                            ArrivalStation = "PEI",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 11, 23, 17, 649, DateTimeKind.Local).AddTicks(5266),
                            DepartureStation = "BOG",
                            Price = 108373m,
                            TransportId = 12
                        },
                        new
                        {
                            Id = 13,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 5, 23, 17, 649, DateTimeKind.Local).AddTicks(5269),
                            DepartureStation = "PEI",
                            Price = 232990m,
                            TransportId = 13
                        },
                        new
                        {
                            Id = 14,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 2, 12, 23, 17, 649, DateTimeKind.Local).AddTicks(5272),
                            DepartureStation = "PEI",
                            Price = 236346m,
                            TransportId = 14
                        },
                        new
                        {
                            Id = 15,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 7, 23, 17, 649, DateTimeKind.Local).AddTicks(5275),
                            DepartureStation = "BOG",
                            Price = 220240m,
                            TransportId = 15
                        },
                        new
                        {
                            Id = 16,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 9, 23, 17, 649, DateTimeKind.Local).AddTicks(5319),
                            DepartureStation = "BOG",
                            Price = 254986m,
                            TransportId = 16
                        },
                        new
                        {
                            Id = 17,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 12, 23, 17, 649, DateTimeKind.Local).AddTicks(5323),
                            DepartureStation = "BOG",
                            Price = 183217m,
                            TransportId = 17
                        },
                        new
                        {
                            Id = 18,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 7, 23, 17, 649, DateTimeKind.Local).AddTicks(5330),
                            DepartureStation = "MED",
                            Price = 108963m,
                            TransportId = 18
                        },
                        new
                        {
                            Id = 19,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 10, 23, 17, 649, DateTimeKind.Local).AddTicks(5333),
                            DepartureStation = "MED",
                            Price = 114957m,
                            TransportId = 19
                        },
                        new
                        {
                            Id = 20,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 12, 23, 17, 649, DateTimeKind.Local).AddTicks(5338),
                            DepartureStation = "MED",
                            Price = 140624m,
                            TransportId = 20
                        },
                        new
                        {
                            Id = 21,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 5, 23, 17, 649, DateTimeKind.Local).AddTicks(5341),
                            DepartureStation = "CTG",
                            Price = 179157m,
                            TransportId = 21
                        },
                        new
                        {
                            Id = 22,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 10, 23, 17, 649, DateTimeKind.Local).AddTicks(5344),
                            DepartureStation = "CTG",
                            Price = 140812m,
                            TransportId = 22
                        },
                        new
                        {
                            Id = 23,
                            ArrivalStation = "CTG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 9, 23, 17, 649, DateTimeKind.Local).AddTicks(5348),
                            DepartureStation = "BOG",
                            Price = 120082m,
                            TransportId = 23
                        },
                        new
                        {
                            Id = 24,
                            ArrivalStation = "CTG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 12, 23, 17, 649, DateTimeKind.Local).AddTicks(5352),
                            DepartureStation = "BOG",
                            Price = 182951m,
                            TransportId = 24
                        },
                        new
                        {
                            Id = 25,
                            ArrivalStation = "PEI",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 5, 23, 17, 649, DateTimeKind.Local).AddTicks(5355),
                            DepartureStation = "BOG",
                            Price = 296283m,
                            TransportId = 25
                        },
                        new
                        {
                            Id = 26,
                            ArrivalStation = "PEI",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 11, 23, 17, 649, DateTimeKind.Local).AddTicks(5359),
                            DepartureStation = "BOG",
                            Price = 130376m,
                            TransportId = 26
                        },
                        new
                        {
                            Id = 27,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 5, 23, 17, 649, DateTimeKind.Local).AddTicks(5362),
                            DepartureStation = "PEI",
                            Price = 250390m,
                            TransportId = 27
                        },
                        new
                        {
                            Id = 28,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 3, 12, 23, 17, 649, DateTimeKind.Local).AddTicks(5366),
                            DepartureStation = "PEI",
                            Price = 207788m,
                            TransportId = 28
                        },
                        new
                        {
                            Id = 29,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 7, 23, 17, 649, DateTimeKind.Local).AddTicks(5370),
                            DepartureStation = "BOG",
                            Price = 125538m,
                            TransportId = 29
                        },
                        new
                        {
                            Id = 30,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 9, 23, 17, 649, DateTimeKind.Local).AddTicks(5374),
                            DepartureStation = "BOG",
                            Price = 155922m,
                            TransportId = 30
                        },
                        new
                        {
                            Id = 31,
                            ArrivalStation = "MED",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 12, 23, 17, 649, DateTimeKind.Local).AddTicks(5377),
                            DepartureStation = "BOG",
                            Price = 161133m,
                            TransportId = 31
                        },
                        new
                        {
                            Id = 32,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 7, 23, 17, 649, DateTimeKind.Local).AddTicks(5381),
                            DepartureStation = "MED",
                            Price = 252037m,
                            TransportId = 32
                        },
                        new
                        {
                            Id = 33,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 10, 23, 17, 649, DateTimeKind.Local).AddTicks(5483),
                            DepartureStation = "MED",
                            Price = 202058m,
                            TransportId = 33
                        },
                        new
                        {
                            Id = 34,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 12, 23, 17, 649, DateTimeKind.Local).AddTicks(5492),
                            DepartureStation = "MED",
                            Price = 281553m,
                            TransportId = 34
                        },
                        new
                        {
                            Id = 35,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 5, 23, 17, 649, DateTimeKind.Local).AddTicks(5495),
                            DepartureStation = "CTG",
                            Price = 265449m,
                            TransportId = 35
                        },
                        new
                        {
                            Id = 36,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 10, 23, 17, 649, DateTimeKind.Local).AddTicks(5499),
                            DepartureStation = "CTG",
                            Price = 181726m,
                            TransportId = 36
                        },
                        new
                        {
                            Id = 37,
                            ArrivalStation = "CTG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 9, 23, 17, 649, DateTimeKind.Local).AddTicks(5502),
                            DepartureStation = "BOG",
                            Price = 108422m,
                            TransportId = 37
                        },
                        new
                        {
                            Id = 38,
                            ArrivalStation = "CTG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 12, 23, 17, 649, DateTimeKind.Local).AddTicks(5506),
                            DepartureStation = "BOG",
                            Price = 181426m,
                            TransportId = 38
                        },
                        new
                        {
                            Id = 39,
                            ArrivalStation = "PEI",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 5, 23, 17, 649, DateTimeKind.Local).AddTicks(5510),
                            DepartureStation = "BOG",
                            Price = 285744m,
                            TransportId = 39
                        },
                        new
                        {
                            Id = 40,
                            ArrivalStation = "PEI",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 11, 23, 17, 649, DateTimeKind.Local).AddTicks(5513),
                            DepartureStation = "BOG",
                            Price = 294465m,
                            TransportId = 40
                        },
                        new
                        {
                            Id = 41,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 5, 23, 17, 649, DateTimeKind.Local).AddTicks(5517),
                            DepartureStation = "PEI",
                            Price = 234406m,
                            TransportId = 41
                        },
                        new
                        {
                            Id = 42,
                            ArrivalStation = "BOG",
                            Currency = "COP",
                            DepartureDate = new DateTime(2020, 11, 4, 12, 23, 17, 649, DateTimeKind.Local).AddTicks(5520),
                            DepartureStation = "PEI",
                            Price = 113006m,
                            TransportId = 42
                        });
                });

            modelBuilder.Entity("NewShore.Domain.Model.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("NamePasanger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailContact = "mariobot@hotmail.com",
                            FlightId = 10,
                            NamePasanger = "Mario Botero",
                            PhoneNumber = "5764821565"
                        },
                        new
                        {
                            Id = 2,
                            EmailContact = "cmejia@hotmail.com",
                            FlightId = 20,
                            NamePasanger = "Carolina gomez",
                            PhoneNumber = "5732456215"
                        },
                        new
                        {
                            Id = 3,
                            EmailContact = "mmejia@gmail.com",
                            FlightId = 30,
                            NamePasanger = "Maria Mejia",
                            PhoneNumber = "5755662245"
                        },
                        new
                        {
                            Id = 4,
                            EmailContact = "fernando23@gmail.com",
                            FlightId = 40,
                            NamePasanger = "Fernanda Ferrero",
                            PhoneNumber = "57545562"
                        },
                        new
                        {
                            Id = 5,
                            EmailContact = "cmejia@hotmail.com",
                            FlightId = 42,
                            NamePasanger = "Camilo Mejia",
                            PhoneNumber = "574455665"
                        });
                });

            modelBuilder.Entity("NewShore.Domain.Model.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightNumber = "JFZDACJ"
                        },
                        new
                        {
                            Id = 2,
                            FlightNumber = "DDNSALN"
                        },
                        new
                        {
                            Id = 3,
                            FlightNumber = "WBNUFKR"
                        },
                        new
                        {
                            Id = 4,
                            FlightNumber = "WPGYRLG"
                        },
                        new
                        {
                            Id = 5,
                            FlightNumber = "WUPYRZX"
                        },
                        new
                        {
                            Id = 6,
                            FlightNumber = "PJSJAJR"
                        },
                        new
                        {
                            Id = 7,
                            FlightNumber = "WGOATRT"
                        },
                        new
                        {
                            Id = 8,
                            FlightNumber = "JGILIYN"
                        },
                        new
                        {
                            Id = 9,
                            FlightNumber = "QTEIQDG"
                        },
                        new
                        {
                            Id = 10,
                            FlightNumber = "JYTIMQH"
                        },
                        new
                        {
                            Id = 11,
                            FlightNumber = "RULEBZZ"
                        },
                        new
                        {
                            Id = 12,
                            FlightNumber = "IRXYUMN"
                        },
                        new
                        {
                            Id = 13,
                            FlightNumber = "NHNJAKZ"
                        },
                        new
                        {
                            Id = 14,
                            FlightNumber = "QNBJGLN"
                        },
                        new
                        {
                            Id = 15,
                            FlightNumber = "IURGBMR"
                        },
                        new
                        {
                            Id = 16,
                            FlightNumber = "LXHHZOH"
                        },
                        new
                        {
                            Id = 17,
                            FlightNumber = "BGKWRTV"
                        },
                        new
                        {
                            Id = 18,
                            FlightNumber = "QGZMFIB"
                        },
                        new
                        {
                            Id = 19,
                            FlightNumber = "GJVVOLA"
                        },
                        new
                        {
                            Id = 20,
                            FlightNumber = "XGRTAVB"
                        },
                        new
                        {
                            Id = 21,
                            FlightNumber = "KFBAVRO"
                        },
                        new
                        {
                            Id = 22,
                            FlightNumber = "HQMPRRR"
                        },
                        new
                        {
                            Id = 23,
                            FlightNumber = "OSUVDPF"
                        },
                        new
                        {
                            Id = 24,
                            FlightNumber = "NMMLCHE"
                        },
                        new
                        {
                            Id = 25,
                            FlightNumber = "ATDQXTG"
                        },
                        new
                        {
                            Id = 26,
                            FlightNumber = "AXLKQMZ"
                        },
                        new
                        {
                            Id = 27,
                            FlightNumber = "TIFWUII"
                        },
                        new
                        {
                            Id = 28,
                            FlightNumber = "NWYWFWW"
                        },
                        new
                        {
                            Id = 29,
                            FlightNumber = "TPOSJKG"
                        },
                        new
                        {
                            Id = 30,
                            FlightNumber = "XJYTXLN"
                        },
                        new
                        {
                            Id = 31,
                            FlightNumber = "VIKMDFU"
                        },
                        new
                        {
                            Id = 32,
                            FlightNumber = "DGOIZVN"
                        },
                        new
                        {
                            Id = 33,
                            FlightNumber = "WFTRXKH"
                        },
                        new
                        {
                            Id = 34,
                            FlightNumber = "HXRHCTV"
                        },
                        new
                        {
                            Id = 35,
                            FlightNumber = "ZHCWXVR"
                        },
                        new
                        {
                            Id = 36,
                            FlightNumber = "ONJCRCP"
                        },
                        new
                        {
                            Id = 37,
                            FlightNumber = "JZKKOSB"
                        },
                        new
                        {
                            Id = 38,
                            FlightNumber = "DEBAAGN"
                        },
                        new
                        {
                            Id = 39,
                            FlightNumber = "LTFAMYE"
                        },
                        new
                        {
                            Id = 40,
                            FlightNumber = "ZLLCAWH"
                        },
                        new
                        {
                            Id = 41,
                            FlightNumber = "RJOGHRY"
                        },
                        new
                        {
                            Id = 42,
                            FlightNumber = "XGXNATV"
                        });
                });

            modelBuilder.Entity("NewShore.Domain.Model.Flight", b =>
                {
                    b.HasOne("NewShore.Domain.Model.Transport", "Transport")
                        .WithMany("Flights")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewShore.Domain.Model.Ticket", b =>
                {
                    b.HasOne("NewShore.Domain.Model.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
